#!/bin/bash
# vi: ft=sh

MODE=$1

FILE_NAME=$(date "+%Y-%m-%d.md")

commit_changes() {
	CURRENT_WD=$(pwd)
	cd $1 && git add $2 && git commit -m "Change $2" && git push -q && cd $CURRENT_WD
}

pull_changes() {
	CURRENT_WD=$(pwd)
	cd $1 && git pull -q && cd $CURRENT_WD
}

create_file() {
	FULL_PATH="$1/$2"
	# echo $FULL_PATH
	nvim $FULL_PATH && commit_changes $1 $2
}

search() {
	grep -RIin "$1" $2 --colour | grep -v "(Done)"
}


if [[ -z $JOURNALS_PATH ]]; then
	echo "JOURNALS_PATH is not defined"
	exit 1
fi
if [[ -z $NOTES_PATH ]]; then
	echo "NOTES_PATH is not defined"
	exit 1
fi
if [ "$MODE" = "j" ]; then
	create_file $JOURNALS_PATH $FILE_NAME
	
elif [ "$MODE" = "n" ]; then
	create_file $NOTES_PATH $FILE_NAME
elif [ "$MODE" = "sync" ]; then
	pull_changes $JOURNALS_PATH
	pull_changes $NOTES_PATH
	echo "Syncd!"
elif [ "$MODE" = "search" ]; then
	search $2 $JOURNALS_PATH
	search $2 $NOTES_PATH
	echo "Search Finsihed!"
else
	echo "Unknown command"
	exit 1
fi
